# Generated by Django 5.0.6 on 2024-08-15 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Album', '0002_alter_album_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
