# Generated by Django 5.0.6 on 2024-08-15 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Musicians_directory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
